# Generated by Django 6.0.6 on 2026-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=8),
        ),
        migrations.AddField(
            model_name='membership',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
